### ISSUE TITLE
Reapack

### ISSUE THREAD

**Issue by mrlimbic** [chkhld/jsfx#1]
Have you thought about turning your github repositories into reapack repositories to make them easier for people to install and keep up to date?

https://reapack.com/

**Comment by pms967** [comment]
+1

**Comment by chkhld** [comment]
I have thought about it, yes. I've even looked into it, but I quite simply have no clue how it works, and it's such a drag finding any useful information in a digestible format. It seems to be so much d*cking around, not just to set up, but also to maintain. 

Reorganize my repository, download some tool, run it over a local working copy of the repository, add its result to my repository, commit that again. Just to get going. Whenever I change something, I essentially have to go through the whole thing again. At least that's how I understand it.

It already starts with the local working copy of this repository, which I don't have. When I'm done writing a plugin, I log in to GitHub and create a new file, paste the text in, that's it. I don't feel like keeping multiple copies of this repo on my various computers, as I already have copies of the JSFX files in my Reaper directory, so that's good and un-redundant enough for me.

It all just seems like an awful lot of trouble to go to, for me as the developer, after I already went through all the trouble of coding the things and providing them for free in the first place, you know. It doesn't hurt people to figure out how to open Reaper's resource folder, create a text file and paste some text. ;) 

Maybe someday someone will be able to provide a simpler mechanism, or instructions I can actually be bothered to try to understand. It's not that I'm not open to the whole idea, but as I wrote in the main Readme.md: _This is just a fun project for me, I do this on the side to waste time or template C++ code, so don't expect too much of an effort._

If you come across any less confusing resources and instructions than an 11-page forum thread from several years ago, with nearly every post contradicting one of the previous in some way, then please feel free to share. :)

**Comment by mrlimbic** [comment]
I agree the documentation isn't great. If you like I can show you how sometime. It's a bit of a pain to set up but once done then additions/updates are easy.

**Comment by chkhld** [comment]
Well, if you know a simple tutorial "for dummies" like myself, then please let me know.
Checked Website, Forums, Youtube ... didn't find any instructions straight-forward enough for me yet.

**Comment by D34dmeat** [comment]
try the template:  https://github.com/cfillion/reapack-repository-template
worked like a charm for me (on simple test projects),

**Comment by myrrc** [comment]
I made a fork of this repository with ReaPack index: https://github.com/myrrc/chkld_jsfx

**Comment by myrrc** [comment]
If you wish, you can use this script from my repository to change your scripts to be indexed by Reapack https://github.com/myrrc/chkld_jsfx/blob/master/convert.py

**Comment by chkhld** [comment]
Fi-ner-lee!
https://github.com/chkhld/jsfx#installation

Now, next step, how do I get my repo into ReaPack by default, without users having to manually add it? :)

@myrrc Thank you kindly for your effort. 👍 But I managed to get everything running here on my own. I spent some more work on the file headers, sorted all the plugins into categories, simplified the README.md, hosted the screenshots in the repository, etc.

@D34dmeat I experimented with that template, and while the "check" action seemed to always complete successfully, the "deploy" action always failed. No clue why. Could it have been because the repository (an experimental copy) was set to "private" at the time?

**Comment by myrrc** [comment]
One option is to write to @cfillion and ask to add this repo as a default one to reapack/reapack. Another is to build reapack from https://github.com/cfillion/reapack/pull/69 and import a text index with your repo without manual mouse clicking.

**Comment by cfillion** [comment]
> how do I get my repo into ReaPack by default, without users having to manually add it?

It can be added to the list of known free third-party repositories on https://reapack.com/repos.

Effects can be uploaded to the community ReaTeam JSFX repository (https://reapack.com/upload/jsfx or via pull requests) to be available out of the box. (However that's probably not the best suggestion for a large unified collection of effects like yours – maintaining your own repo is better for that.)

No new default third-party repositories are accepted at this time (randomly adding some would be unfair and just adding everyone's repos would lead to a mess and many headaches (security, user support...)).

> I experimented with that template, and while the "check" action seemed to always complete successfully, the "deploy" action always failed

Is "Workflow permissions" set to "Read and write" and "Allow actions created by GitHub" and "Allow actions by Marketplace verified creators" enabled under Settings > Actions?

**Comment by chkhld** [comment]
I was typing an email to you while your message here was already waiting for me. Safe to discard that email, since everything relevant is handled here. :)

I've forked, updated, pull-requested, looks like it was accepted and merged already, so my repo is now in the list of known third-party repos. I can see the link on the ReaPack website, so I guess that's as good as it gets.

Quite honestly, I have absolutely no idea what actions and workflows and all those things are, that's all way too enterprise-y for me so far. To me, GitHub is a code dump that makes sure I don't lose the code and others can access it, didn't need it for anything else thus far.

It would make more sense to me to just create a Docker image with Ruby, pandoc and reapack-index on it, and just fire that up whenever I need the indexer, rather than figuring out what hidden setting of a feature I know nothing about could possibly be obstructing execution of something else I know nothing about... :)

The main thing is: the repo is on ReaPack, as was originally requested by @mrlimbic in the OP.

Thank you to everyone who kept nudging and poking, you finally got what you wanted, I hope everyone's happy now. ;)
