### ISSUE TITLE
Knee Clipper graphics bug

### ISSUE THREAD

**Issue by cue-zephyr** [chkhld/jsfx#5]
Dear chkhld,

Sometimes when I load Knee Clipper, the graphics look like this instead of the I/O levels.

![image](https://user-images.githubusercontent.com/34492834/223549453-4d091423-ad8e-42b0-b2d8-de6de6f1d9b4.png)

Thank you for an awesome plugin, though!

**Comment by chkhld** [comment]
Hi @cue-zephyr

I know it's been a while, but I finally had some time to spend to look into this. I could recreate the problem here, and I believe I could fix it. Please update your installation to the latest version, and let me know if you still experience this issue.

Here's a link to the plugin code directly:
https://github.com/chkhld/jsfx/blob/main/Clipper/knee_clipper.jsfx

And of course, since the latest update, you can now also install this via ReaPack.

**Comment by samlletas** [comment]
I was going to create a new issue but found this was already reported. It seems the problem is still present in the latest version, I noticed the fix added in 9cda735de2cdbf282a33bddec8a44c5354a32123 was later removed in 07a0be084c99b278e868146bc7eb7892b2434390.

This bug happens when pressing play, but resizing the plugin's window afterwards seems to fix it (this has to be done each time after pressing play), perhaps this problem is related to gfx recalculation?
